### ISSUE TITLE
Success Profile pie chart

### ISSUE THREAD

**Issue by dfoerst** [radancyco/tmp-custom-imports#5]
The pie chart is adding extra padding at the bottom of the page. If I take out the "UL" for the pie chart, the space is not there at the bottom of the page.

It is noticeable on this ajd: https://phsajobs-v2.runmytests.com/job/vancouver/registered-nurse-registered-psychiatric-nurse-bc-children-s-mental-health/909/10974723

Screen capture from Daniel - https://www.screencast.com/t/NCAWkHkn - Daniel mention either the script or the tooltips.

**Comment by Brockenstein** [comment]
Fixed in f23da060
